language: python
python:
  - "2.7"
  - "3.6"

install:
  - "pip install -r tests/requirements.txt"

env:
  - PYTHONPATH=.

# command to run tests
script:
  - python -m unittest discover teststests/travis/run.sh
